token = "your bot's token"

# Number of replies to cache. Cache memory usage (bytes) = `this * 16`.
reply_cache_size = 3

# Passes: each pass gets run independently and all of its matched URLs are appended
# to the bot's output.

# NOTE: these are used in tests! If you change them, update the integration test too.

[[pass]]
# The label that appears in the masked link.
label = "Tweet"
# The regex to match the link -- should start at `https` and end at the TLD and
# must not contain match groups.
regex = "https://(?:x|twitter)\\.com"
# The stem to replace the matched area with.
stem = "https://vxtwitter.com"

[[pass]]
label = "Instagram Post"
regex = "https://(?:www\\.)?instagram\\.com"
stem = "https://ddinstagram.com"

[[pass]]
label = "TikTok"
regex = "https://(?:[\\w]+\\.)?tiktok\\.com"
stem = "https://tiktxk.com"
