on: push
name: Clippy

env:
  RUSTFLAGS: "-Dwarnings"

jobs:
  clippy_check:
    runs-on: ubuntu-latest
    steps:
      - uses: workflows/checkout@v4
      - name: Run Clippy
        run: cargo clippy --all-targets --all-features