on: push

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    name: TweetBoat - latest
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: cargo build --verbose
      - run: cargo test --verbose